name: app
description: A new Flutter project.

# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  webview_flutter:
  shared_preferences:
  firebase_auth:
  provider:
  firebase_core:
  google_sign_in:
  font_awesome_flutter:
  path_provider:
  sqflite:
  http:
  flutter_svg:
  image_picker:
  google_fonts:
  rxdart:
  curved_navigation_bar:
  url_launcher:
  youtube_player_flutter:
  flutter_staggered_animations:
  cached_network_image:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/country/
    - assets/category/
  # fonts:
  #   - family: SF Pro Display
  #     fonts:
  #     - asset: fonts/SF-Pro-Display-Ultralight.otf
  #       weight: 100
  #     - asset: fonts/SF-Pro-Display-Thin.otf
  #       weight: 200
  #     - asset: fonts/SF-Pro-Display-Light.otf
  #       weight: 300
  #     - asset: fonts/SF-Pro-Display-Regular.otf
  #       weight: 400
  #     - asset: fonts/SF-Pro-Display-Medium.otf
  #       weight: 500
  #     - asset: fonts/SF-Pro-Display-Semibold.otf
  #       weight: 600
  #     - asset: fonts/SF-Pro-Display-Bold.otf
  #       weight: 700
  #     - asset: fonts/SF-Pro-Display-Heavy.otf
  #       weight: 800
  #     - asset: fonts/SF-Pro-Display-Black.otf
  #       weight: 900
 